In [9]:
import pandas as pd
import numpy as np

In [2]:
gap = pd.read_csv('gap_mider.csv')

In [8]:
gap.loc[:,['BMI']]

BMI
0    20.62058
1    26.44657
2    24.59620
3    27.63048
4    22.25083
5    25.35542
6    27.56373
7    26.46741
8    25.65117
9    27.24594
10   20.39742
11   26.38439
12   26.16443
13   26.75915
14   27.02255
15   22.41835
16   22.82180
17   24.43335
18   26.61163
19   22.12984
20   25.78623
21   26.54286
22   21.27157
23   21.50291
24   20.80496
25   23.68173
26   27.45210
27   23.51522
28   21.48569
29   27.01542
..        ...
133  27.49975
134  21.96671
135  22.40484
136  25.49887
137  23.16969
138  26.37629
139  26.20195
140  26.91969
141  23.77966
142  22.47792
143  23.00803
144  20.59082
145  21.87875
146  30.99563
147  26.39669
148  25.15699
149  26.70371
150  25.24796
151  22.35833
152  25.42379
153  28.05359
154  27.39249
155  28.45698
156  26.39123
157  25.32054
158  26.78926
159  26.57750
160  20.91630
161  20.68321
162  22.02660

[163 rows x 1 columns]

In [10]:
syn0 = 2*np.random.random((3,1)) - 1

In [44]:
np.array([[5,4,3]]).shape

(1, 3)

In [33]:
matr.max()

5

In [34]:
matr.shape[1]

2

In [51]:
inputs = np.array([0.7, -0.3])
weights = np.array([0.1, 0.8])

In [54]:
x = np.array([1, 2, 3, 4])
w = np.array([0.5, -0.5, 0.3, 0.1])

In [55]:
x*w

array([ 0.5, -1. ,  0.9,  0.4])

In [56]:
np.dot(x,w)

0.79999999999999982

In [58]:
def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))


# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))


# TODO: Make a forward pass through the network

hidden_layer_in = np.dot(X, weights_input_to_hidden)
hidden_layer_out = sigmoid(hidden_layer_in)

In [63]:
weights_input_to_hidden

array([[-0.02341534, -0.0234137 ,  0.15792128],
       [ 0.07674347, -0.04694744,  0.054256  ],
       [-0.04634177, -0.04657298,  0.02419623],
       [-0.19132802, -0.17249178, -0.05622875]])

In [64]:
hidden_layer_in

array([-0.34365494, -0.29801368,  0.00097362])

In [66]:
hidden_layer_out

array([ 0.41492192,  0.42604313,  0.5002434 ])

In [ ]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)

## Backwards pass
## TODO: Calculate error
error = target - output

# TODO: Calculate error gradient for output layer
del_err_output = error * output * (1 - output)

# TODO: Calculate error gradient for hidden layer
del_err_hidden = weights_hidden_output * del_err_output * hidden_layer_output *(1- hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * del_err_output * x[:, None]

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * del_err_hidden * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)